image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "dotnet test"
        - echo "testing"

deploy:
    stage: deploy
    variables:
        deploy_path: "NewsAPI/"
    artifacts:
        paths:
            - NewsAPI/bin/release
    script:
        - cd $deploy_path
        - dotnet publish -c release