image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test
    - deploy

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "dotnet test"
        - echo "testing"

deploy:
    stage: deploy
    variables:
        deploy_path: "NewsAPI/"
    artifacts:
        paths:
            - /builds/153064/newsapp-step3-boilerplate/NewsAPI/bin/release/netcoreapp3.1/NewsAPI.dll
    script:
        - cd $deploy_path
        - dotnet publish -c release